services:
# Continer 1: FirstAPI
  server:
    build:
      context: .  # Dockerfile for the server should be in this directory
    container_name: fastapi_server
    ports:
      - 8001:8001  # Maps port 8001 on the host to 8001 in the container
    networks:
      - closed-network
    depends_on:
      postgres_db:
        condition: service_healthy  # Waits until postgres_db passes healthcheck

# Continer 2: Postgres
  postgres_db:
    image: postgres  # Uses the official PostgreSQL image
    restart: always
    user: postgres
    container_name: pg_db
    volumes:
      - db-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data
    environment:
      - POSTGRES_DB=example  # Initializes the database
      - POSTGRES_PASSWORD=mysecretpassword  # Sets the default password
    networks:
      - closed-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]  # Checks database readiness
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  closed-network:
    driver: bridge

volumes:
  db-data:
    driver: local
